# /etc/hostapd.conf

# https://git.w1.fi/cgit/hostap/plain/hostapd/hostapd.conf
# https://wireless.docs.kernel.org/en/latest/en/users/documentation/hostapd.html

interface=wlan0
driver=nl80211
ssid=test
channel=40

hw_mode=a
wpa_passphrase=password

macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
